/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecurrencesRouteImport } from './routes/recurrences'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InstallmentsRouteImport } from './routes/installments'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrencesRoute = RecurrencesRouteImport.update({
  id: '/recurrences',
  path: '/recurrences',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsRoute = InstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/recurrences': typeof RecurrencesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/recurrences': typeof RecurrencesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/recurrences': typeof RecurrencesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/chat'
    | '/dashboard'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/installments'
    | '/invoices'
    | '/login'
    | '/recurrences'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/transactions'
    | '/api/chat'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/chat'
    | '/dashboard'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/installments'
    | '/invoices'
    | '/login'
    | '/recurrences'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/transactions'
    | '/api/chat'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budgets'
    | '/chat'
    | '/dashboard'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/installments'
    | '/invoices'
    | '/login'
    | '/recurrences'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/transactions'
    | '/api/chat'
    | '/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  InstallmentsRoute: typeof InstallmentsRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  RecurrencesRoute: typeof RecurrencesRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrences': {
      id: '/recurrences'
      path: '/recurrences'
      fullPath: '/recurrences'
      preLoaderRoute: typeof RecurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments': {
      id: '/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof InstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  InstallmentsRoute: InstallmentsRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  RecurrencesRoute: RecurrencesRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
